### ISSUE TITLE
Madoko vs LaTeX

### ISSUE THREAD

**Issue by jrappen** [mdipierro/nlib#19]
@mdipierro FYI there is `madoko`:

* via npm
* <https://www.madoko.net>
* <https://github.com/koka-lang/madoko>
  * <https://github.com/koka-lang/madoko/blob/gh-pages/reference.pdf>
* <https://www.microsoft.com/en-us/research/video/madoko-a-scholarly-markdown>

which might be an easier format for the source of the PDF.

**Comment by mdipierro** [comment]
I invented markmin for this purpose and I used it for the web2py book. None of them is good enough to replace the power of latex. Sticking to latex. :-)
